export const allResponses = [
  "i'm not autistic... i think",
  "what?",
  "i'm confused",
  "FUUUUUCK! My poor cunt",
  "i love sizzy rocket moaning",
  "Wrabel is my crush",
  "Are you Sizzy Rocket? Because I get wet at thought of you",
  "this is a red flag i love a red flag",
  "the journey is usually the part you remember anyways",
  "ooh girl the broccoli sprouts",
  "italizzo's here i need to kill her",
  "okay so you hate me...",
  "not you calling me fat omg",
  "i'm about to be burping bubbles",
  "i'm so awful i love myself",
  "i'm so wonderful i hate myself",
  "https://cdn.discordapp.com/attachments/1008810118424572035/1450933588261605478/togif.gif?ex=69c23df4&is=69c0ec74&hm=a5d6495a9265f9779aa01fbcb31c61f847ae5bad1cce7312a6440410a83358df&",
  "Katy Perry dominate me pls",
  "OH GIRL... also italizzo was here today for some reason",
  "I don't know what that is",
  "only if you're keshasebert2311",
  "ja po prostu nie lubię swojej twarzy dopóki nie będę wyglądać z twarzy jak demi lovato to nigdy nie zaakceptuję tej twarzy albo dopóki nie usunę sobie kompleksów z twarzy to do tej pory nie będę akceptować",
  "YOU RUIN EVERYTHING JLO",
  "yassss beer for dinner #skinny",
  "oh ok",
  "yes i am thank u!",
  "OH THAT",
  "Being Silesian is tough",
  "i don't want a funeral or any remembrance of me so just throw me in the jungle",
  "omg my babies",
  "*Demi fucking Lovato*.",
  "WHEN I CATCH YOUR ASS.......",
  "PUSH THE ICE PICK IN RIGHT THE FUCK NOW.",
  "lizzo music's so powerful 💗",
  "An asylum, Khia or otherwise, patient going by the name of britkneexcx has escaped, currently roaming the streets of Tel Aviv. Beware of uninvited queefs.",
  "https://cdn.discordapp.com/attachments/893232745680101463/1463272144807923815/IMG_6623.png?ex=69c98e61&is=69c83ce1&hm=b7fffdfd7042d9ee2b1e06e6af53404cb9bae28d769cd679435392a98c227467&",
  "Dropping my new song monday if this gets 100k retweets!",
  "i just got a brand new tour. hose me down at the asylum. we lit up like a dumpster fire. singing yippee-ki-yay yippee-katy-ya. the sales are low. i'm already chopped. that wig you got go on and put it on. to sell out tours is impossible. put my record on ... and mute it",
  "I will sell my Tel Aviv show ticket for Lifetimes Tour.",
  "You fucking CUM SWALLOWER U ALWAYS BULLY ME !",
  "https://cdn.discordapp.com/attachments/1443723676741668997/1480949100240175146/krzyk_vid.mp4?ex=69ca9554&is=69c943d4&hm=429c2737f46d2a7e41c1bb14b0f04aab36d8706eade7d99f00c8509d78e2220f&",
  "<@1354911987225723051> topped me on February 30th, 1987.",
  "i have unexplored whimsy i'm ready for my interview",
  "there is something so inherently wrong with me",
  "just take it out on me.... 🙁",
  "going with <@1354911987225723051> to lifetimes tour show in Tel Aviv im so fucking excited yass bitch",
  "@ddlovato NO MORE BRAIN DAMAGE",
  "<@1032649573199523900> hannah baker yourself",
  "i'm in my F4G ASS JEANS",
  "britknee wants to top me 🙁",
  "am i jealous of rita ora jesus fuck i need to be gone from this world",
  "NO QUEEFING AND/OR POLISH ALLOWED.",
  "🫱(‿¤‿)🫲",
  "stream Leicester Bush 💋",
  "TELIZZY AVIV-ROCKET STATUS: APPROVED!",
  "||BITCH YOU THOUGHT||",
  "i will commit 9/11 in tel aviv",
  "Pre-save my new album. 💜 https://lizzo.lnk.to/bitch",
  "Out now. 💗 https://open.spotify.com/album/18JIUrWc9SN596q2Km9KSJ?si=w7PmJVEYSb6O7CjC4tW9Wg",
  "I feel turned on!",
  "MORE SIZZY GOONINGS PLEASE",
];

export const dinnerAnswers = [
  "beer",
  "nothing fatso",
  "broccoli sprouts",
  "kefir",
  "eat my ass",
  "girl idk what am i a chef",
  "sizzy rocket's kitty 😝",
  "i don't remember",
];

export const askAdrianAnswers = [
  "YES BITCH",
  "NO",
  "only if Sizzy Rocket approves",
  "Only if you're keshasebert2311",
  "never bitch.",
  "ask Christine",
  "ask KeshaBot",
  "i don't know",
  "i don't remember",
  "leave me alone bitch",
  "uh oh, my dick is stuck in dishwasher (that means no)",
  "OFC YES",
  "all I know is that it's <@1378383649396883519> fault",
  "Yess daddy 🤤",
  "Nicki Minaj tanked (that means ask Royce)",
  "TELIZZY AVIV-ROCKET STATUS: APPROVED!",
  "TELIZZY AVIV-ROCKET STATUS: DENIED",
];

export const pingResponses = allResponses;
export const commandResponses = allResponses;

export function getRandomResponse(responses: string[]): string {
  return responses[Math.floor(Math.random() * responses.length)];
}
